### ISSUE TITLE
extremely minor issue with your example

### ISSUE THREAD

**Issue by edwardsmarkf** [wzrdtales/node-dynamic-columns#3]
your main example is missing a comma:

uuid: 122
    name: 'test'

sorry to bring this up i did a cut/paste of your example and had an error.  you may want to consider fixing that.

thank you so much for creating node-dynamic-columns.  i was working on one myself when i came across yours.   

i am trying to use sequelize.js but they dont really seem to have JSON support (yet)

**Comment by wzrdtales** [comment]
Good catch! Will have a look on this later on.

Thanks for reporting :)

**Comment by edwardsmarkf** [comment]
you might consider including an example something like this:

{ 'one'  : 'data for one\'; DROP TABLE FakeTable; }

the people at sequelize are naturally concerned about SQLI - i suggested your work on their slack page and that was the first concern they raised.

i should think that so long as all back-slashes are removed and then single-quotes are backslashed, this would be enough to sanitize all incoming stuff.  but maybe i am being naive?

**Comment by edwardsmarkf** [comment]
4-got to mention:   updateQuery - i learned something new!  thank you very much.

fyi: i am combining sequelize.js with deepstream.io to create something of a mariaDB framework, and your fantastic github contribution is working perfectly.   next up, join this with vue.js or matreshka.io

**Comment by wzrdtales** [comment]
@edwardsmarkf Yes, SQLi might be a valid concern. But actually this is not always something a module needs to or even should handle. Protection against SQLi and other injection attacks, starts with proper validation of input though. I am concerned about security, though. Don't hesitate if you discover any securiy issue (naturally mail me directly to not disclose it publicly...)

The escaping of bad characters is actually placed over here: https://github.com/wzrdtales/node-dynamic-columns/blob/master/lib/index.js#L119-L122, but you're always better off to use the prepared statement mode, which this module does already support. Also to mention that it might not be obvious how to actually use it, I haven't added examples for this yet.

**Comment by wzrdtales** [comment]
Basically it is:

``` javascript
    let data = { some: 'thing' };
    let prepared = [];
    let dyn = dyncol.createQuery( data, true, prepared );

    sql.query( 'INSERT INTO `order` (`data`) VALUES (' + dyn + ')',
      prepared, function(err, results ) {

    });
```

**Comment by wzrdtales** [comment]
You need to pass an empty array into the function, this was made like this, to keep this lib backwards compatible. We return the query, so we don't can just return an object with the data array and the query part instead without breaking everything.

**Comment by wzrdtales** [comment]
The first version was released without support for prepared statements, so actually this being the reason for the design. If I decide to release a new major version with breaking changes, I would probably return both in an array/object instead.

**Comment by wzrdtales** [comment]
Just fixed your mentioned typo :)

**Comment by edwardsmarkf** [comment]
hey thanks !

i cant really imagine any sql-injection issues that you have not already
dealt with.

> > >   Protection against SQLi and other injection attacks, starts with
> > > proper validation of input

i will include a preliminary check into my code on your advice.

a guy in the sequelize slack room works in money exchange so naturally he
is very concerned about SQLi.  i dont think he fully appreciates CREATE_XXX
 (actually he does not approve it it anyways).

your github module is now in place, it eliminated quite a bit of my clumsy
code and shortened my overall script.   life is good !

i am eager now to tie an EASY framework into

Thank you,

Mark Edwards

**Comment by wzrdtales** [comment]
@edwardsmarkf I still wait for mariadb to implement native json parsing ;) I wonder if this ever gets a released though.

Actually you also helped without knowing to identify a security issue, it just hit me when I watched your harmless SQLi example. that I did not catched one case yet ;) Also it is very unlikely, but I did not escaped the fields yet, it is very unlikely that anybody would allow a user to pass in his own fields, but who knows, everything is possible.

But actually only in the non prepared statement mode, the prepared statement mode is actually the safest thing you can get, as this are really just prepared statements that are being created. You get your query with lots of question marks and your passed array gets filled with the proper values. The rest is up to the prepared statement logic of the driver.

However I also released a fix for this, thanks for bringing this to my attention, also you did not know you did ;)

**Comment by wzrdtales** [comment]
@edwardsmarkf 

>  i dont think he fully appreciates CREATE_XXX (actually he does not approve it it anyways).

You mean `COLUMN_CREATE`? Could be very possible that you hit on someone that does not like the movement of `NoSQL`, `NewSQL` and `Graphs` otherwise I don't know where his problem is. The only problem I see in dynamic columns of mariadb currently is, that there is still no proper support to index those ;)

**Comment by edwardsmarkf** [comment]
in the united states, we have a saying:

"actually i already knew it, i was just MAKING SURE you did too"  - it
helps us to save face occasionally (recent example would be politics).

this will help you to understand American culture.  or help you to want to
avoid it.

Thank you,

Mark Edwards

**Comment by edwardsmarkf** [comment]
> > You mean COLUMN_CREATE? Could be very possible that you hit on someone
> > that does not like the movement of NoSQL, NewSQL and Graphs
> > otherwise I don't know where his problem is. The only problem I see in
> > dynamic columns of mariadb currently is, that there is still no proper
> > support to index those ;)

that debate is getting a little religious...  ;-)    admittedly, when i
first looked at meteor-mongodb my first question was "where the hell is the
referential integrity??"

rethink-db seems to have addressed this one, at least a little bit.  i am
probably going to slowly and cautiously move to rethink-db but i still am
going to seriously miss my referential integrity checking.  the M:N (or
what i like to call parent-->child<--parent ) relationships are so common.

the driving force for me is easy FRAMEWORKS - and i really dont want a php
solution (sorry laravel).     horizon.io looks like it might be the best
option, assuming i can get rethinkDB to work.

Thank you,

Mark Edwards

**Comment by wzrdtales** [comment]
@edwardsmarkf Ok :) That came a bit random know as I don't know in which context you try to put your phrase right now ;)

**Comment by wzrdtales** [comment]
@edwardsmarkf 

>  "where the hell is the referential integrity??"

This is something you only need within the DB, if you can't control it in your own logic. Controlling it in your own logic, is much more easy to scale and even more often also way more performant than doing it on the database. And sometimes one just don't need it.

You should have a look at NewSQL btw. For example spanner or cockroachdb, those will get very interesting in the near future, especially the latter one.

**Comment by edwardsmarkf** [comment]
you:

> > >  However I also released a fix for this, thanks for bringing this to my
> > > attention, also _you did not know you did_ ;)

me:   "actually i already knew it, i was just MAKING SURE you did too"

i think we are typing over each-other.

but all that being said, i now have a deepstream--sequelize--dyncol
 "mini-framework" working - so its time to go celebrate.   once again, i
want to thank you.

Thank you,

Mark Edwards

**Comment by wzrdtales** [comment]
@edwardsmarkf And yes agreeing, it gets a bit "religious". At least arguing against new features b/c they don't conform with traditional SQL is "religious". I always try to keep out of such conversations, as they are not productive at all.
RDBMS have their use case and NoSQL have their use case, so there is no one or another, there might be a better RDBMS than x, but there is no way to compare it against NoSQL which has its own issues and benefits. So it really doesn't make sense to fight against any of those...

**Comment by edwardsmarkf** [comment]
> > >  NewSQL

awesome - once again, thank you!   honestly, first time i have heard of it.
  any names you recommend yet?

did you get my email i sent to "magic@wizardtales.com"   ?   there is
another missing comma in your next example, same page (attaching it here
too)

and sql vs no-sql debate (and now newSql- thanks)  - i would be very happy
if i could just have the following:

1) some sort of referential integrity enforcement for
_parent-->child<--parent_  type relationships (in some cases
i actually have three parents)

2) node-based framework (i am tired of php)

so, any framework names or NewSQL names you can recommend would
be appreciated very much.  my next long layover in Frankfurt might include
an expensive dinner for you as a gift for helping me....!

Thank you,

Mark Edwards

**Comment by wzrdtales** [comment]
@edwardsmarkf 

> attention, also _you did not know you did_ ;)
> 
> me:   "actually i already knew it, i was just MAKING SURE you did too"

Ok, in this case this is a strange phrase to place. Especially in case of security concerns. If one really would have knowledge of something like such stuff he should report it immediately, for the better of all.  So I was really confused of your phrase, b/c you did not report an issue, but I discovered another one. I do work with people from the U.S.A. everyday, but I nerver encountered anyone saying something like this. Ironically, from my view, putting this sentence in a dialogue like this in that context would result in the quite opposite of what you was stating. In actually loosing face. In Germany it is actually rude to pretend something in this manner after it has occured when you were not actually reporting it.

**Comment by wzrdtales** [comment]
@edwardsmarkf 

> node-based framework (i am tired of php)

Most of us are..., and especially secfolks love php. At least they love to audit applications written in php. 
One of my favourite blog posts why PHP is so... well I don't have words for it:
http://eev.ee/blog/2012/04/09/php-a-fractal-of-bad-design/

> did you get my email i sent to "magic@wizardtales.com"   ?   there is another missing comma in your next example, same page (attaching it here too)

Yes got it, going to fix that ;)

**Comment by wzrdtales** [comment]
@edwardsmarkf And I have listed two NewSQL examples already :)
- Spanner
- CockroachDB

There is also `voltDB`, but haven't put my hands on it yet, so I can't say anything about it.

**Comment by edwardsmarkf** [comment]
> > >   In Germany it is actually rude to pretend something in this manner
> > > after it has occured when you were not actually reporting it.

it probably is considered rude in the USA too - but that explains why
everybody always thinks i am so rude !

i will look into spanner & cockroachdb (if i can get past the name).
 thanks.

Thank you,

Mark Edwards

**Comment by wzrdtales** [comment]
@edwardsmarkf 

> node-based framework 

You would need to list a bit what you need.
The most awesome thing about node.js is actually the package culture. There is something for nearly everything. So it is not just always about frameworks, but modules that are useful for your project.

What I can recommend is hapi.js as a framework for web applications. It does a lot for you that you would need to manually implement in express and it also is much cleaner in my opinion. But this is just my opinion you should obviously decide on this for yourself.
And when I say hapi.js i  actually mean hapi.js and the whole stuff around hapi.js. There are quite a lot modules from the hapi.js makers intended to be used with hapi.js.

For example:
- joy (input validation)
- lab (a test framework)
- crumb (csrf token, yeah security again :) )

And I also recommend `seneca.js` if you're going to work on microservices :)

**Comment by wzrdtales** [comment]
Btw. for any other typos or other stuff you discover, you can also feel free to open a PR ;)

**Comment by wzrdtales** [comment]
@edwardsmarkf 

> cockroachdb (if i can get past the name)

There could be better names, but they thought it would fit, as they work on a database that could survive a nuclear war. Cross Datacenter is a huge and important topic for them and mostly NewSQL in general though.

**Comment by edwardsmarkf** [comment]
hey- i hope you are not getting tired of me thanking you!

interesting naming there....

it sounds as if you seem to prefer data-storage and frameworks that are
really somewhat independent of each-other, connected merely by node.js ?

Thank you,

Mark Edwards

**Comment by wzrdtales** [comment]
@edwardsmarkf 
Well yes. 
In my opinion a framework should never do too much. It should be useful, for a single kind of thing, it shouldn't be bloated, but extensible and carefully designed. Unfortunately, most stuff that calls itself a framework is exactly this, bloated.

And no not just connected by node.js. I also use protocols (mostly simple tcp packet structures, like classic header, length, checksum, content packets) for the communication of independent services, that may not be written in Node.js but for example C. It always depends on the use case for me though.

**Comment by wzrdtales** [comment]
@edwardsmarkf 
To add: Bloated and most often also terribly slow: Hello there Laravel and Eloquent ;)
